### PR TITLE
Implement always compare mode for hash library

### PR DESCRIPTION
**Pull request by Cadair**
Useful for CI so you can see the changes from the reference images even if the hash library has been updated

### CODE REVIEW

**Comment by Cadair** [comment]
Needs tests.

**Comment by ConorMacBride** [comment]
I've rebased locally and this PR conflicts with #121 so need to need to find a way around that.

**Comment by ConorMacBride** [comment]
The hash libraries for mpl20, mpl21, mpl22 and mpl30 are using ft2104 even though Matplotlib apparently hasn't changed the Freetype library in 6 years: https://github.com/matplotlib/matplotlib/blame/085fdd0771c01ccf964459033904d31bf79e611a/lib/matplotlib/__init__.py#L1191

I don't understand how this could have worked before but I'll rename the libraries to have ft261 and update the hashes where necessary. Let me know if I have missed something.

**Comment by ConorMacBride** [comment]
@Cadair Can you review please?

**Pull request merged**
