### PR TITLE
Package infrastructure cleanup

### PR DESCRIPTION
**Pull request by astrofrog**
This PR does the following:

* Switches to using setup.cfg to declare most package metadata
* Improves the tox configuration
* Switches to the CI to Travis-only for all platforms
* Switches the CI to use tox
* Removes Matplotlib and Pillow as required dependencies for the plugin - there are cases where one might want to install the plugin without necessarily pulling in Matplotlib and Pillow too.
* Remove nose dependency - this is only needed for old Matplotlib versions (<2.1). I don't think we need to explicitly disallow those versions, but people using those can always install nose manually if needed

For now I haven't dropped Python 2.7 support but we could technically do that too (though at this point it wouldn't provide many benefits)

### CODE REVIEW

**Comment by dopplershift** [comment]
I’m curious: how does one use this plugin without matplotlib?

**Comment by bsipocz** [comment]
@dopplershift - one doesn't, but I think the ideas is to be able to install this plugin no matter whether mpl is around or not rather than to use the plugin (e.g. this could be added to the `pytest-astropy` metapackage, but we can keep on testing astropy without mpl (which is an optional dependency).

**Comment by dopplershift** [comment]
I’m still missing something. This feels like solving what is a downstream packaging issue by breaking pytest-mpl’s packaging. Here’s what I see:

1. Pytest-mpl is a “plugin to facilitate image comparison for Matplotlib figures in pytest.”
2. This PR proposes no longer requiring matplotlib
3. User installs pytest-mpl, but gets no functionality whatsoever

I’m open to tweaking the dependencies if there are gains for our users. All I’m hearing is this makes it easier for pytest-astropy to depend on it unconditionally. I’m not seeing an argument for how our users benefit from this change—in fact, all I see is a path to where users can get non-functional environments and us getting increased support questions. So, what functionality does pytest-mpl give users if matplotlib is not installed?

**Comment by dopplershift** [comment]
My point here is that if you don’t have functionality without matplotlib, I cease to see a reasonable argument for why matplotlib should not be listed as a dependency. I get why this might make life nice for pytest-astropy; I don’t see why it’s sound software engineering or kind to non-astropy users.

**Comment by bsipocz** [comment]
I agree that this is not a clear cut, but @astrofrog might have better arguments than me. For pytest-mpl I see that the users are developers, and in many cases, developers of packages that have mpl as an optional dependency. Their life would be easier if they could just list pytest-mpl as a test dependency for their packages, as keep the mpl dependency optional, also in their testing framework and CI rather than keep mpl _and_ pytest-mpl as optional dependency for testing.

**Comment by astrofrog** [comment]
I can see arguments both ways, but in the interest of getting the infrastructure cleanup merged in I've added back Matplotlib as a required dependency for now.

**Comment by bsipocz** [comment]
My only comment is to drop python2, as part of the cleanup.

**Comment by astrofrog** [comment]
I've dropped Python 2.7 and 3.5, as well as Matplotlib 1.5.

**Comment by astrofrog** [comment]
@dopplershift - thanks! I'm happy with it as-is, so will merge now.

**Pull request merged**
