### PR TITLE
Started implementing support for deterministic figure output

### PR DESCRIPTION
**Pull request by astrofrog**
This is a work in progress and not ready for review

### CODE REVIEW

**Comment by astrofrog** [comment]
This should be ready for review. One question is whether this should actually be the default, at least for the new supported formats. For PNG we would break people's tests if they have different baseline images for different matplotlib versions and were not setting the Software: None metadata. But for the new formats it might be sensible?

**Review by ConorMacBride — APPROVED** [review]
Brilliant! I think this definitely should be the default. There are some other breaking changes I think should be made to make the plugin less sensitive and easier to manage, particularly for new users: use the default matplotlib style, merge the perceptual hashing and make it the default hash type when generating a new library, and maybe review some of the ini, cli and decorator settings for consistency. We could start preparing for a `v1.0.0` in a new branch. What do you think?

**Comment by astrofrog** [comment]
@ConorMacBride - thanks for reviewing! I'm a little uncertain how we should approach breaking changes at this point, but of the changes you mention I agree that if we could make breaking changes, then switching the default Matplotlib style would be good. Perhaps also changing the default tolerance to 0. However I'm not sure about making perceptual hashes the default, I still feel that should probably be opt-in? In any case perhaps we could open a new issue to discuss it?

**Comment by astrofrog** [comment]
Or at the very least we'll need to have deprecation warnings in place for a little while before we actually break things.

**Pull request merged**
